"""
Safety Guardrails for Emergency Triage System
Non-negotiable safety rules and mandatory escalation logic
"""

import re
from typing import Dict, List, Tuple
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent))
import config


class SafetyGuardrails:
    """
    Enforces safety rules and mandatory escalation policies
    """
    
    def __init__(self):
        self.critical_symptoms = [s.lower() for s in config.CRITICAL_SYMPTOMS]
        self.high_risk_symptoms = [s.lower() for s in config.HIGH_RISK_SYMPTOMS]
    
    def check_critical_symptoms(self, text: str) -> Tuple[bool, List[str]]:
        """
        Check if text contains any critical symptoms requiring immediate escalation
        
        Args:
            text: Patient input text (complaint, transcript, etc.)
            
        Returns:
            (has_critical, list_of_found_symptoms)
        """
        text_lower = text.lower()
        found_symptoms = []
        
        for symptom in self.critical_symptoms:
            if symptom in text_lower:
                found_symptoms.append(symptom)
        
        return len(found_symptoms) > 0, found_symptoms
    
    def enforce_emergency_override(self, case_data: Dict, ml_prediction: Dict) -> Dict:
        """
        Apply safety guardrails to ML prediction
        Overrides ML output if critical symptoms detected
        
        Args:
            case_data: Patient case information
            ml_prediction: Original ML model output
            
        Returns:
            Modified prediction with safety overrides applied
        """
        result = ml_prediction.copy()
        overrides_applied = []
        
        # Check for critical symptoms in transcript
        transcript = case_data.get('transcript', '')
        has_critical, critical_found = self.check_critical_symptoms(transcript)
        
        if has_critical:
            result['risk_score'] = 1.0
            result['confidence'] = 1.0
            result['is_emergency'] = True
            result['recommendation'] = 'EMERGENCY - Dispatch ambulance'
            result['safety_override'] = True
            overrides_applied.append(f"Critical symptoms detected: {', '.join(critical_found)}")
        
        # Check consciousness status
        if not case_data.get('conscious', True):
            result['risk_score'] = 1.0
            result['is_emergency'] = True
            result['safety_override'] = True
            overrides_applied.append("Patient unconscious - automatic emergency escalation")
        
        # Check extreme pain levels
        pain_level = case_data.get('pain_level', 0)
        if pain_level >= 9:
            result['risk_score'] = max(result['risk_score'], 0.90)
            result['is_emergency'] = True
            overrides_applied.append(f"Extreme pain level ({pain_level}/10)")
        
        # Check very young or very old
        age = case_data.get('age', 0)
        if age < 1 and result['risk_score'] > 0.5:
            result['risk_score'] = max(result['risk_score'], 0.85)
            result['is_emergency'] = True
            overrides_applied.append("Infant patient - elevated to emergency")
        
        # Low confidence bias
        if result['confidence'] < config.CONFIDENCE_THRESHOLD:
            if result['risk_score'] >= 0.40:  # Even moderate risk becomes emergency
                result['risk_score'] = max(result['risk_score'], config.EMERGENCY_THRESHOLD + 0.05)
                result['is_emergency'] = True
                overrides_applied.append("Low confidence - safety-first escalation")
        
        # Add override information
        if overrides_applied:
            result['safety_overrides'] = overrides_applied
            result['original_ml_score'] = ml_prediction.get('risk_score')
            
            # Update reasoning
            override_text = " | ".join(overrides_applied)
            result['reasoning'] = f"SAFETY OVERRIDE: {override_text} | {result.get('reasoning', '')}"
        
        return result
    
    def validate_genai_output(self, genai_output: str) -> Tuple[bool, str]:
        """
        Validate that GenAI output doesn't contain prohibited content
        
        Args:
            genai_output: Text generated by GenAI system
            
        Returns:
            (is_valid, error_message)
        """
        # Prohibited phrases that indicate diagnosis or treatment
        prohibited_phrases = [
            "you have",
            "i think you have",
            "i diagnose",
            "this is definitely",
            "you need to take",
            "take this medication",
            "my diagnosis is",
            "you should treat",
        ]
        
        output_lower = genai_output.lower()
        
        for phrase in prohibited_phrases:
            if phrase in output_lower:
                return False, f"Prohibited content detected: '{phrase}' - GenAI cannot diagnose or prescribe"
        
        # Check for medical advice red flags
        medical_advice_keywords = [
            "prescribe",
            "prescription",
            "medication dosage",
            "take this drug",
        ]
        
        for keyword in medical_advice_keywords:
            if keyword in output_lower:
                return False, f"Medical advice detected: '{keyword}' - prohibited in intake mode"
        
        return True, ""
    
    def check_mandatory_fields(self, case_data: Dict) -> Tuple[bool, List[str]]:
        """
        Verify all required fields are present
        
        Args:
            case_data: Patient case data
            
        Returns:
            (all_present, list_of_missing_fields)
        """
        missing = []
        
        for field in config.REQUIRED_INTAKE_FIELDS:
            if field not in case_data or case_data[field] is None:
                missing.append(field)
        
        return len(missing) == 0, missing
    
    def sanitize_input(self, user_input: str) -> str:
        """
        Sanitize user input to prevent injection attacks
        
        Args:
            user_input: Raw user input
            
        Returns:
            Sanitized input string
        """
        # Remove any potential code injection
        sanitized = re.sub(r'[<>{}]', '', user_input)
        
        # Limit length
        max_length = config.INPUT_VALIDATION['max_text_length']
        if len(sanitized) > max_length:
            sanitized = sanitized[:max_length]
        
        # Remove excessive whitespace
        sanitized = ' '.join(sanitized.split())
        
        return sanitized
    
    def emergency_bias_check(self, risk_score: float, confidence: float) -> bool:
        """
        Determine if emergency bias should be applied
        
        Args:
            risk_score: Original ML risk score
            confidence: Model confidence
            
        Returns:
            True if should escalate to emergency
        """
        # Low confidence + moderate risk = emergency
        if confidence < config.CONFIDENCE_THRESHOLD and risk_score >= 0.40:
            return True
        
        # Very low confidence = always emergency
        if confidence < 0.50:
            return True
        
        return False


class HumanOverride:
    """
    Manages human override functionality
    """
    
    @staticmethod
    def create_override_record(
        case_id: str,
        original_recommendation: str,
        human_decision: str,
        reason: str,
        operator_id: str
    ) -> Dict:
        """
        Create a record when human overrides AI recommendation
        
        Returns:
            Override record for audit log
        """
        return {
            'case_id': case_id,
            'original_ai_recommendation': original_recommendation,
            'human_decision': human_decision,
            'override_reason': reason,
            'operator_id': operator_id,
            'override_timestamp': str(pd.Timestamp.now()),
        }
    
    @staticmethod
    def validate_override_reason(reason: str) -> bool:
        """
        Ensure override reason is substantive
        
        Args:
            reason: Override reason text
            
        Returns:
            True if valid reason provided
        """
        if not reason or len(reason.strip()) < 10:
            return False
        return True


# Import pandas for timestamp
import pandas as pd


if __name__ == "__main__":
    # Test safety guardrails
    print("=== Testing Safety Guardrails ===\n")
    
    guardrails = SafetyGuardrails()
    
    # Test 1: Critical symptom detection
    test_cases = [
        "I have severe chest pain and can't breathe",
        "My ankle hurts from twisting it",
        "Patient is unconscious and not responding",
        "Just a mild headache",
    ]
    
    for i, test in enumerate(test_cases, 1):
        has_critical, symptoms = guardrails.check_critical_symptoms(test)
        print(f"Test {i}: {test}")
        print(f"  Critical: {has_critical}")
        if symptoms:
            print(f"  Found: {symptoms}")
        print()
    
    # Test 2: GenAI output validation
    prohibited_outputs = [
        "You have pneumonia and should take antibiotics",
        "Based on symptoms, this sounds like a minor issue",
        "I think you have the flu",
    ]
    
    print("\n=== GenAI Output Validation ===\n")
    for output in prohibited_outputs:
        is_valid, error = guardrails.validate_genai_output(output)
        print(f"Output: {output}")
        print(f"  Valid: {is_valid}")
        if error:
            print(f"  Error: {error}")
        print()
    
    print("✓ Safety guardrail tests complete")
